test for invalid uaa access token

diff --git a/pivnet-upload b/pivnet-upload
--- a/pivnet-upload
+++ b/pivnet-upload
@@ -33,23 +33,33 @@ shopt -s expand_aliases
 
 alias uaac='BUNDLE_GEMFILE=/home/tempest-web/tempest/web/vendor/uaac/Gemfile bundle exec uaac'
 
+# TODO: grab these from .pivnetrc ?
 OPSMAN_USER=admin
+CLIENT_ID=opsman
+CLIENT_SECRET=
 
 error_and_exit() {
   echo $1 >&2
   exit 1
 }
 
-UAA_ACCESS_TOKEN=$(uaac context $OPSMAN_USER | grep access_token | awk '{ print $2 }')
+is_valid_access_token() {
+  local accessToken=$1
 
-if [ -z "$UAA_ACCESS_TOKEN" ]; then
-  echo "UAA Access Token: "
-  read -r UAA_ACCESS_TOKEN
-fi
+  [ -n "$accessToken" ] || return 1
 
+  local statusCode=$(curl http://localhost/uaa/check_token -k -L -G \
+    -s -o /dev/null -w "%{http_code}" \
+    -u "$CLIENT_ID:$CLIENT_SECRET" \
+    -d token_type=bearer \
+    -d token="$accessToken")
+
+    [ "200" = "$statusCode" ]
+}
+
+# Prompt for the file if the user didn't specify it
 if [ -z "$1" ]; then
-  echo "Local file name: "
-  read -r LOCAL_FILE_NAME
+  read -r -p "Local file name: " LOCAL_FILE_NAME
 else
   LOCAL_FILE_NAME=$1
 fi
@@ -57,6 +67,13 @@ fi
 if [ ! -f "$LOCAL_FILE_NAME" ]; then
   error_and_exit "Invalid file: $LOCAL_FILE_NAME"
 fi
+
+# Login to UAA if we don't have a valid token
+UAA_ACCESS_TOKEN=$(uaac context $OPSMAN_USER | grep access_token | awk '{ print $2 }')
+
+[ ! $(which uaac-loginx) ] && echo "Cannot find 'uaac-login'. Please install it from opsman-scripts!"
+
+[ ! is_valid_access_token ] && uaac-login
 
 curl "https://localhost/api/v0/available_products" \
   -k -# -o /dev/null \
